CREATE TABLE `story_drafts` (
	`id` text PRIMARY KEY NOT NULL,
	`title_en` text NOT NULL,
	`title_zh` text NOT NULL,
	`excerpt_en` text NOT NULL,
	`excerpt_zh` text NOT NULL,
	`genres_en` text NOT NULL,
	`genres_zh` text NOT NULL,
	`author_id` text,
	`new_author_name` text,
	`new_author_mode` text,
	`new_author_tagline_en` text,
	`new_author_tagline_zh` text,
	`new_author_bio_en` text,
	`new_author_bio_zh` text,
	`source_id` text,
	`new_source_title_en` text,
	`new_source_title_zh` text,
	`new_source_original_author` text,
	`new_source_first_published` text,
	`new_source_proposal` text,
	`new_source_adaptation_note_en` text,
	`new_source_adaptation_note_zh` text,
	`chapters_json` text NOT NULL,
	`revision_reason_en` text,
	`revision_reason_zh` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
